version: 1
disable_existing_loggers: False

formatters:
  minimal:
    format: "%(message)s"
  detailed:
    format: "%(levelname)s %(asctime)s [%(filename)s:%(funcName)s:%(lineno)d] %(message)s"
  json:
    # class: pythonjsonlogger.jsonlogger.JsonFormatter
    '()': pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(timestamp)s %(level)s %(name)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: detailed
    level: INFO
  info:
    class: logging.handlers.RotatingFileHandler
    filename: ${LOGS_DIR}/info.log
    maxBytes: 10485760  # 1 MB
    backupCount: 10
    formatter: detailed
    level: INFO
    encoding: utf-8
  json_file:
    class: logging.handlers.RotatingFileHandler
    filename: ${LOGS_DIR}/log.json
    maxBytes: 10485760  # 1 MB
    backupCount: 10
    formatter: json
    level: INFO
    encoding: utf-8
  error:
    class: logging.handlers.RotatingFileHandler
    filename: ${LOGS_DIR}/error.log
    maxBytes: 10485760  # 1 MB
    backupCount: 10
    formatter: detailed
    level: ERROR
    encoding: utf-8

loggers:
  root:
    handlers: [console, info, error]
    level: INFO
    propagate: True
  uvicorn:
    handlers: [console, info, error]
    level: DEBUG
    propagate: False
